[build]
builder = "NIXPACKS"

[nix]
pkgs = [
    "pango",
    "cairo",
    "gdk-pixbuf",
    "gobject-introspection", # La librería clave que faltaba
    "fontconfig"             # Importante para que encuentre las fuentes del sistema
]