[build]
builder = "NIXPACKS"

[nix]
# Usaremos aptPkgs en lugar de pkgs. Es un método más directo.
aptPkgs = [
    "libpango-1.0-0",
    "libpangoft2-1.0-0",
    "libgobject-2.0-0",
    "libfontconfig1"
]